version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://skyhelper:NezoX228008!@db:5432/anonloader
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: anonloader
      POSTGRES_USER: skyhelper
      POSTGRES_PASSWORD: NezoX228008!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  anon_bot:
    build: .
    command: python manage.py anon
    depends_on:
      - db
      - web  # Убедитесь, что бот запускается после веб-сервиса
    volumes:
      - .:/app

  support_bot:
    build: .
    command: python manage.py support
    depends_on:
      - db
      - web  # Убедитесь, что бот запускается после веб-сервиса
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A file_sharing worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  flower:
    build: .
    command: celery -A file_sharing flower
    volumes:
      - .:/app
    depends_on:
      - celery
      - web
    ports:
    - "5555:5555"  # Добавьте эту строку

  celery_beat:
    build: .
    command: celery -A file_sharing beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - web


volumes:
  postgres_data:
